name: On Pull Request Workflow

on:
  pull_request:
    branches: [master]

jobs:
  check-coverage-regression:
    name: Check for coverage regression
    runs-on: ubuntu-latest

    steps:
    - name: Set PR coverage manually
      run: echo "94.5" > pr-coverage

    - name: Download master coverage metric
      id: download-master-coverage
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: on-merge.yml
        name: master-coverage
        if_no_artifact_found: warn
    - name: Checking for coverage regression
      run: |
        CURRENT_COVERAGE=$(cat pr-coverage)
        if [ -s master-coverage ]; then
            MASTER_COVERAGE=$(cat master-coverage)
            echo "Master coverage is at $MASTER_COVERAGE"
            echo "PR coverage is at $CURRENT_COVERAGE"
            COMPARISON="$CURRENT_COVERAGE>=$MASTER_COVERAGE"
            echo "Coverage comparison: $COMPARISON"
            if [ $(echo $COMPARISON | bc) -eq 1 ]; then
                echo "PR coverage greater than or equal to Master coverage. Ok to proceed."
            else
                echo "PR coverage less than Master coverage. Failing build."
                exit 1
            fi
        else
            echo "No previous coverage metric found. Current coverage is $CURRENT_COVERAGE"
        fi
    - name: Add Coverage detail to step description
      run: |
        CURRENT_COVERAGE=$(cat pr-coverage)
        curl "https://${secrets.GIT_USER}:${secrets.GITHUB_TOKEN}@api.github.com/repos/${ORG_NAME}/${PROJECT_NAME}/statuses/${COMMIT_SHA}" -d "{\"state\": \"${STATE}\",\"target_url\": \"https://github.com/${ORG_NAME}/${PROJECT_NAME}/pull/${PULL_NUMBER}/checks?check_run_id=${RUN_ID}\",\"description\": \"${CURRENT_COVERAGE}%\",\"context\": \"code cov\"}"
        env:
            TOTAL: ${{ steps.check-coverage.outputs.total }}
            GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
            GIT_USER: ${{ secrets.GIT_USER }}
            ORG_NAME: ${{ secrets.ORG_NAME }}
            PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
            COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
            RUN_ID: ${{ github.run_id }}
            PULL_NUMBER: ${{ github.event.pull_request.number }}
    - name: Upload PR coverage metric
      uses: actions/upload-artifact@v2
      with:
        name: pr-coverage
        path: pr-coverage
        if-no-files-found: error