name: On Pull Request Workflow

on:
  pull_request:
    branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - run: echo "91" > pr-coverage
    - name: Download master coverage from any branch (only generated on MERGE)
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: on-merge.yml
        name: master-coverage
        if_no_artifact_found: warn
    - run: |
        echo "Master coverage is at $(cat master-coverage)"
        echo "PR coverage is at $(cat pr-coverage)"
        COMPARISON="$(cat pr-coverage)<$(cat master-coverage)"
        echo $COMPARISON
        if [ $(echo $COMPARISON | br) -eq 1 ]; then
            echo "PR coverage less than Master coverage. Failing build."
            exit 1
    - name: Upload artifact - (Branch specific)
      uses: actions/upload-artifact@v2
      with:
        name: pr-coverage
        path: pr-coverage