name: On Pull Request Workflow

on:
  pull_request:
    branches: [master]

jobs:
  check-coverage-regression:
    name: Check for coverage regression
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write

    steps:
    - name: Set PR coverage manually
      id: set-pr-coverage
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        PR_COVERAGE_FILE="pr-$PR_NUMBER-coverage"
        echo "pr_coverage_file=$PR_COVERAGE_FILE" >> "$GITHUB_OUTPUT"
        echo "97.5" > $PR_COVERAGE_FILE

    - name: Download master coverage metric
      uses: actions/download-artifact@v3
      id: download
      with:
        name: master-coverage

    - name: Display structure of downloaded files
      run: ls -R
    
    - name: Checking for coverage regression
      id: check-coverage
      run: |
        CURRENT_COVERAGE=$(printf "%.2f" $(cat ${{ steps.set-pr-coverage.outputs.pr_coverage_file }}))
        DELTA="Unknown"
        REGRESSION=0
        if [ -s master-coverage ]; then
            MASTER_COVERAGE=$(printf "%.2f" $(cat master-coverage))
            COMPARISON="$CURRENT_COVERAGE>=$MASTER_COVERAGE"
            DELTA=$( echo "$CURRENT_COVERAGE - $MASTER_COVERAGE" | bc )
            echo "Master coverage is at $MASTER_COVERAGE"
            echo "PR coverage is at $CURRENT_COVERAGE"
            echo "Delta is at $DELTA"
            echo "Coverage comparison: $COMPARISON"
            if [ $(echo $COMPARISON | bc) -eq 1 ]; then
                echo "PR coverage greater than or equal to Master coverage. Ok to proceed."
            else
                echo "PR coverGge less than Master coverage."
                REGRESSION=1
            fi
        else
            echo "No previous coverage metric found. Current coverage is $CURRENT_COVERAGE"
        fi
        echo "current_coverage=$CURRENT_COVERAGE" >> "$GITHUB_OUTPUT"
        echo "delta=$DELTA" >> "$GITHUB_OUTPUT"
        echo "regression=$REGRESSION" >> "$GITHUB_OUTPUT"
    - name: Comment with coverage details
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        append: true
        message: |
            Run ${{ github.run_number }}: Coverage is now at ${{ steps.check-coverage.outputs.current_coverage }}% (${{ steps.check-coverage.outputs.delta }} delta) - ${{ steps.check-coverage.outputs.regression == 1 && '❌ Regression' || '✅ No regression' }}
    - name: Fail if coverage regression
      run: |
        REGRESSION=${{ steps.check-coverage.outputs.regression }}
        if [ "$REGRESSION" -eq 1 ]; then
            echo "Failing build."
            exit 1
        fi
    - name: Upload PR coverage metric
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.set-pr-coverage.outputs.pr_coverage_file }}
        path: ${{ steps.set-pr-coverage.outputs.pr_coverage_file }}
        if-no-files-found: error